const hpImages = [
  // HOMEPAGE
  {
    id: "home-hero",
    filename: "home-hero.png",
    path: "assets/images/home/home-hero.png",
    page: "home",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 2400,
    sourceHeight: 1350,
    alt: "A diverse family interacting with a HealthPlus medical professional in a bright modern clinic",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "family-wellness",
    filename: "family-wellness.png",
    path: "assets/images/home/family-wellness.png",
    page: "home",
    section: "banner",
    aspectRatio: "21:9",
    sourceWidth: 2400,
    sourceHeight: 1028,
    alt: "A healthy, diverse family in a bright clinic wellness setting",
    focalPointDesktop: "center left",
    focalPointMobile: "center",
    loading: "lazy",
    priority: "auto",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  
  // CORE PAGES
  {
    id: "about-hero",
    filename: "about-hero.png",
    path: "assets/images/core/about-hero.png",
    page: "about",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "Modern clinic architecture with healthcare professionals collaborating naturally",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "team-hero",
    filename: "team-hero.png",
    path: "assets/images/core/team-hero.png",
    page: "team",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A diverse group of medical professionals in a bright clinic environment",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "contact-hero",
    filename: "contact-hero.png",
    path: "assets/images/core/contact-hero.png",
    page: "contact",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A warm receptionist welcoming visitors in a clean medical reception space",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "appointment-hero",
    filename: "appointment-hero.png",
    path: "assets/images/core/appointment-hero.png",
    page: "book",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A healthcare professional and patient having a calm consultation",
    focalPointDesktop: "center left",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },

  // INTERIORS
  {
    id: "reception",
    filename: "reception.png",
    path: "assets/images/interiors/reception.png",
    page: "various",
    section: "interiors",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A bright, clean, and modern medical clinic reception area",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "lazy",
    priority: "auto",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "consultation-room",
    filename: "consultation-room.png",
    path: "assets/images/interiors/consultation-room.png",
    page: "various",
    section: "interiors",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A sophisticated and natural consultation room in a modern healthcare facility",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "lazy",
    priority: "auto",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "examination-room",
    filename: "examination-room.png",
    path: "assets/images/interiors/examination-room.png",
    page: "various",
    section: "interiors",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A clean, functional examination room with modern diagnostic equipment",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "lazy",
    priority: "auto",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },

  // SERVICES
  {
    id: "family-medicine",
    filename: "family-medicine.png",
    path: "assets/images/services/family-medicine.png",
    page: "service-family-medicine",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A compassionate family physician speaking with a family in a bright consultation room",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "walk-in-clinic",
    filename: "walk-in-clinic.png",
    path: "assets/images/services/walk-in-clinic.png",
    page: "service-walk-in-clinic",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A clean reception environment with welcoming staff assisting a walk-in patient",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "internal-medicine",
    filename: "internal-medicine.png",
    path: "assets/images/services/internal-medicine.png",
    page: "service-internal-medicine",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A physician reviewing health information with an adult patient in a medical consultation room",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "mental-health",
    filename: "mental-health.png",
    path: "assets/images/services/mental-health.png",
    page: "service-mental-health",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A calm, softly lit therapy space with a professional listening attentively to a patient",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "mva-care",
    filename: "mva-care.png",
    path: "assets/images/services/mva-care.png",
    page: "service-mva-care",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A healthcare professional carefully evaluating a patient for mobility and recovery",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "obstetrics-gynecology",
    filename: "obstetrics-gynecology.png",
    path: "assets/images/services/obstetrics-gynecology.png",
    page: "service-obstetrics-gynecology",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A bright, private women's health consultation with a female physician and patient",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "pediatric-care",
    filename: "pediatric-care.png",
    path: "assets/images/services/pediatric-care.png",
    page: "service-pediatric-care",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A pediatrician interacting naturally with a child and parent in a welcoming examination room",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "sports-medicine",
    filename: "sports-medicine.png",
    path: "assets/images/services/sports-medicine.png",
    page: "service-sports-medicine",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A sports medicine professional assessing an active adult in a modern rehabilitation environment",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "virtual-care",
    filename: "virtual-care.png",
    path: "assets/images/services/virtual-care.png",
    page: "service-virtual-care",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A premium telemedicine setup with a physician communicating clearly via laptop screen",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "womens-health",
    filename: "womens-health.png",
    path: "assets/images/services/womens-health.png",
    page: "service-womens-health",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A female healthcare professional discussing preventive health with an adult woman",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },
  {
    id: "concussion-care",
    filename: "concussion-care.png",
    path: "assets/images/services/concussion-care.png",
    page: "service-concussion-care",
    section: "hero",
    aspectRatio: "16:9",
    sourceWidth: 1920,
    sourceHeight: 1080,
    alt: "A clinician conducting a non-invasive neurological assessment using modern diagnostic tools",
    focalPointDesktop: "center right",
    focalPointMobile: "center",
    loading: "eager",
    priority: "high",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  },

  // GLOBAL
  {
    id: "social-share",
    filename: "social-share.png",
    path: "assets/images/global/social-share.png",
    page: "global",
    section: "meta",
    aspectRatio: "1.91:1",
    sourceWidth: 1200,
    sourceHeight: 630,
    alt: "",
    focalPointDesktop: "center",
    focalPointMobile: "center",
    loading: "lazy",
    priority: "auto",
    status: "placeholder",
    approved: false,
    placeholderPath: "assets/images/global/healthplus-placeholder.svg",
    finalAssetRequired: true
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = hpImages;
}
